name: cli-app-release
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  cli-app-release:
    permissions:
      contents: write
    uses: kukushkin/workflows/.github/workflows/github-release.yaml@main
    with:
      write_version: true
      version_filename: version/version.txt
